"""run.py — XORCISM connector SCAFFOLD for honeypots.

25 different honeypots in a single pypi package! (dns, ftp, httpproxy, http, https, imap, mysql, pop3, postgres, redis, smb, smtp, socks5, ssh, telnet, vnc, mssql, elastic, ldap, ntp, memcache, snmp, oracle, sip and irc).
Tool: https://github.com/qeeqbox/honeypots
Category: Honeypot   (XORCISM.TOOL #403)

Generated by connectors/tool_to_connector.py. Implement run() to map honeypots output to
the normalized XORCISM result:
    {"assets": [{"hostname": str, "key": str, "ip": str?, "os": str?}],
     "services": [], "cpes": [], "vulns": [{"asset": str, "ref": str, "name": str, "severity": str}]}
The runner (connectors/runner.py) imports that result. NO database access here (so the
connector also runs on a remote worker).
"""
from __future__ import annotations

from typing import Any, Dict

TOOL_NAME = 'honeypots'
TOOL_URL = 'https://github.com/qeeqbox/honeypots'


def run(params: Dict[str, Any], workdir: str) -> Dict[str, Any]:  # noqa: ARG001
    target = str(params.get("target") or "").strip()
    path = params.get("file")
    # TODO: implement the honeypots integration:
    #   • live mode  -> invoke honeypots against `target` (respect the engagement scope), or
    #   • offline    -> parse the saved output at `path`,
    # then return the normalized result (example shape below).
    raise NotImplementedError(
        f"Connector 'honeypots' ({TOOL_NAME}) is a scaffold - implement run() in "
        f"connectors/honeypots/run.py (tool: {TOOL_URL})."
    )
    # return {"assets": [], "services": [], "cpes": [], "vulns": []}


if __name__ == "__main__":
    import json as _json
    import tempfile
    print(_json.dumps(run({"target": "", "file": None}, tempfile.mkdtemp())))
