"""run.py — XORCISM connector SCAFFOLD for spamd.

spamd
Tool: http://man.openbsd.org/cgi-bin/man.cgi?query=spamd%26apropos=0%26sektion=0%26manpath=OpenBSD+Current%26arch=i386%26format=html
Category: Honeypot   (XORCISM.TOOL #588)

Generated by connectors/tool_to_connector.py. Implement run() to map spamd output to
the normalized XORCISM result:
    {"assets": [{"hostname": str, "key": str, "ip": str?, "os": str?}],
     "services": [], "cpes": [], "vulns": [{"asset": str, "ref": str, "name": str, "severity": str}]}
The runner (connectors/runner.py) imports that result. NO database access here (so the
connector also runs on a remote worker).
"""
from __future__ import annotations

from typing import Any, Dict

TOOL_NAME = 'spamd'
TOOL_URL = 'http://man.openbsd.org/cgi-bin/man.cgi?query=spamd%26apropos=0%26sektion=0%26manpath=OpenBSD+Current%26arch=i386%26format=html'


def run(params: Dict[str, Any], workdir: str) -> Dict[str, Any]:  # noqa: ARG001
    target = str(params.get("target") or "").strip()
    path = params.get("file")
    # TODO: implement the spamd integration:
    #   • live mode  -> invoke spamd against `target` (respect the engagement scope), or
    #   • offline    -> parse the saved output at `path`,
    # then return the normalized result (example shape below).
    raise NotImplementedError(
        f"Connector 'spamd' ({TOOL_NAME}) is a scaffold - implement run() in "
        f"connectors/spamd/run.py (tool: {TOOL_URL})."
    )
    # return {"assets": [], "services": [], "cpes": [], "vulns": []}


if __name__ == "__main__":
    import json as _json
    import tempfile
    print(_json.dumps(run({"target": "", "file": None}, tempfile.mkdtemp())))
