"""run.py — XORCISM connector SCAFFOLD for Capture-HPC-NG.

Capture-HPC-NG
Tool: https://github.com/CERT-Polska/HSN-Capture-HPC-NG
Category: Honeypot   (XORCISM.TOOL #517)

Generated by connectors/tool_to_connector.py. Implement run() to map Capture-HPC-NG output to
the normalized XORCISM result:
    {"assets": [{"hostname": str, "key": str, "ip": str?, "os": str?}],
     "services": [], "cpes": [], "vulns": [{"asset": str, "ref": str, "name": str, "severity": str}]}
The runner (connectors/runner.py) imports that result. NO database access here (so the
connector also runs on a remote worker).
"""
from __future__ import annotations

from typing import Any, Dict

TOOL_NAME = 'Capture-HPC-NG'
TOOL_URL = 'https://github.com/CERT-Polska/HSN-Capture-HPC-NG'


def run(params: Dict[str, Any], workdir: str) -> Dict[str, Any]:  # noqa: ARG001
    target = str(params.get("target") or "").strip()
    path = params.get("file")
    # TODO: implement the Capture-HPC-NG integration:
    #   • live mode  -> invoke Capture-HPC-NG against `target` (respect the engagement scope), or
    #   • offline    -> parse the saved output at `path`,
    # then return the normalized result (example shape below).
    raise NotImplementedError(
        f"Connector 'capture-hpc-ng' ({TOOL_NAME}) is a scaffold - implement run() in "
        f"connectors/capture-hpc-ng/run.py (tool: {TOOL_URL})."
    )
    # return {"assets": [], "services": [], "cpes": [], "vulns": []}


if __name__ == "__main__":
    import json as _json
    import tempfile
    print(_json.dumps(run({"target": "", "file": None}, tempfile.mkdtemp())))
