"""run.py — XORCISM connector SCAFFOLD for telnet-iot-honeypot.

Python telnet honeypot for catching botnet binaries.
Tool: https://github.com/Phype/telnet-iot-honeypot
Category: Honeypot   (XORCISM.TOOL #502)

Generated by connectors/tool_to_connector.py. Implement run() to map telnet-iot-honeypot output to
the normalized XORCISM result:
    {"assets": [{"hostname": str, "key": str, "ip": str?, "os": str?}],
     "services": [], "cpes": [], "vulns": [{"asset": str, "ref": str, "name": str, "severity": str}]}
The runner (connectors/runner.py) imports that result. NO database access here (so the
connector also runs on a remote worker).
"""
from __future__ import annotations

from typing import Any, Dict

TOOL_NAME = 'telnet-iot-honeypot'
TOOL_URL = 'https://github.com/Phype/telnet-iot-honeypot'


def run(params: Dict[str, Any], workdir: str) -> Dict[str, Any]:  # noqa: ARG001
    target = str(params.get("target") or "").strip()
    path = params.get("file")
    # TODO: implement the telnet-iot-honeypot integration:
    #   • live mode  -> invoke telnet-iot-honeypot against `target` (respect the engagement scope), or
    #   • offline    -> parse the saved output at `path`,
    # then return the normalized result (example shape below).
    raise NotImplementedError(
        f"Connector 'telnet-iot-honeypot' ({TOOL_NAME}) is a scaffold - implement run() in "
        f"connectors/telnet-iot-honeypot/run.py (tool: {TOOL_URL})."
    )
    # return {"assets": [], "services": [], "cpes": [], "vulns": []}


if __name__ == "__main__":
    import json as _json
    import tempfile
    print(_json.dumps(run({"target": "", "file": None}, tempfile.mkdtemp())))
